/* KOINOS — production UI controller. Live maps/data are provided by live-core.js. */
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
(()=>{
 const toast=message=>{const n=$('#toast');if(!n)return;n.textContent=message;n.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>n.classList.remove('show'),3200)};
 const modal=$('#report-modal');let currentStep=1;
 const renderStep=step=>{currentStep=step;$$('.report-step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===step));$('#modal-step')&&($('#modal-step').textContent=`0${step} / 04`);$('#modal-progress-bar')&&($('#modal-progress-bar').style.width=`${step*25}%`);if(step===2)window.KOINOS_LIVE?.initReportLocation?.();if(step===4){$('#ai-loading')&&($('#ai-loading').style.display='block');$('#ai-result')?.classList.remove('show');clearTimeout(window.__ai);window.__ai=setTimeout(()=>{$('#ai-loading')&&($('#ai-loading').style.display='none');$('#ai-result')?.classList.add('show')},500)}};
 const openReport=e=>{e?.preventDefault();e?.stopPropagation();if(!modal)return;modal.hidden=false;document.body.style.overflow='hidden';renderStep(1);window.dispatchEvent(new CustomEvent('koinos:report-open'))};
 const closeReport=e=>{e?.preventDefault();e?.stopPropagation();if(!modal)return;modal.hidden=true;document.body.style.overflow='';currentStep=1;$$('.report-step').forEach(x=>x.classList.remove('active'));$('.report-step[data-step="1"]')?.classList.add('active');$('#modal-success')?.classList.remove('show')};
 const ensureLive=()=>new Promise((resolve,reject)=>{if(window.KOINOS_LIVE?.submitReport)return resolve(window.KOINOS_LIVE);let s=document.querySelector('script[data-koinos-live-core]');if(!s){s=document.createElement('script');s.src=`./live-core.js?v=20260906-7`;s.dataset.koinosLiveCore='true';s.onload=()=>window.KOINOS_LIVE?.submitReport?resolve(window.KOINOS_LIVE):reject(Error('Live civic service failed to initialize'));s.onerror=()=>reject(Error('Could not load live civic service'));document.head.appendChild(s)}else{const done=()=>window.KOINOS_LIVE?.submitReport?resolve(window.KOINOS_LIVE):reject(Error('Live civic service failed to initialize'));if(window.KOINOS_LIVE?.submitReport)done();else{s.addEventListener('load',done,{once:true});s.addEventListener('error',()=>reject(Error('Could not load live civic service')),{once:true})}}});
 async function saveReport(closeAfter=false){try{const live=await ensureLive();const result=await live.submitReport();if(!result)return false;if(closeAfter){toast('Report saved to KOINOS.');closeReport();return true}$$('.report-step').forEach(x=>x.classList.remove('active'));$('#modal-success')?.classList.add('show');toast(result.communityMatch?`Connected with ${result.similarIssues?.length||'nearby'} related report(s).`:'Your report is now part of the community record.');return true}catch(err){console.error('KOINOS report flow:',err);toast(err.message||'Report service is unavailable. Please try again.');return false}}
 document.addEventListener('click',async e=>{const report=e.target.closest?.('.report-trigger');if(report){openReport(e);return}const separate=e.target.closest?.('.separate-button');if(separate){e.preventDefault();e.stopImmediatePropagation();await saveReport(true);return}const next=e.target.closest?.('.modal-next');if(next){e.preventDefault();e.stopPropagation();if(currentStep===2&&!await window.KOINOS_LIVE?.confirmLocation?.())return;if(currentStep<4)renderStep(currentStep+1);return}const close=e.target.closest?.('.modal-close,.close-success');if(close){closeReport(e);return}if(e.target===modal)closeReport(e)},true);
 // File picker: delegate from the document so it also works when the report modal is
 // injected after this script runs. Never force camera capture; native browsers can
 // then offer Photos/Gallery/Files as appropriate for the device.
 document.addEventListener('change',e=>{const input=e.target?.closest?.('#photo-upload');if(!input)return;const f=input.files?.[0];if(!f)return;if(!f.type?.startsWith('image/')){input.value='';toast('Please choose an image from Photos, Gallery or Files.');return}if(f.size>12*1024*1024){input.value='';toast('Please choose an image under 12 MB.');return}const fn=$('#file-name');if(fn)fn.textContent=f.name;const take=$('#take-photo');if(take)take.textContent='Change photo';const preview=input.parentElement?.querySelector?.('img[data-upload-preview]')||$('#upload-preview');if(preview){preview.src=URL.createObjectURL(f);preview.hidden=false}toast('Photo selected.');},true);
 document.addEventListener('click',e=>{const take=e.target.closest?.('#take-photo');if(take){e.preventDefault();e.stopPropagation();const input=document.querySelector('#photo-upload');if(!input){toast('Photo picker is not available on this page. Please reload.');return}input.removeAttribute('capture');input.removeAttribute('capturemode');input.setAttribute('accept','image/*,.heic,.heif');input.click();return}const suggestion=e.target.closest?.('[data-suggestion]');if(suggestion){const input=$('#report-description');if(input){input.value=`${input.value?input.value+' ':''}${suggestion.dataset.suggestion}.`;input.focus()}}},true);
 document.addEventListener('click',async e=>{const support=e.target.closest?.('.support-button');if(support){e.preventDefault();const id=support.dataset.issueId;if(!id){toast('Choose an issue on the map first.');return}const result=await window.KOINOS_LIVE?.upvote(id);if(!result){toast('Could not add your support. Try again.');return}const count=result.upvotes??0;$('#affected-count')&&($('#affected-count').textContent=count);$('.support-note')&&($('.support-note').textContent=`${count} people have confirmed this problem.`);support.dataset.supported='true';support.innerHTML="You're affected too <span>✓</span>";toast('Your voice was added to this community issue')}const filter=e.target.closest?.('.filter-button');if(filter){$$('.filter-button').forEach(x=>x.classList.remove('active'));filter.classList.add('active');window.KOINOS_LIVE?.filterMap(filter.dataset.filter||'all')}},false);
 window.addEventListener('koinos:issue',e=>{const issue=e.detail||{},card=$('#selected-issue');if(!card)return;card.querySelector('h3')&&(card.querySelector('h3').textContent=issue.title||'Civic issue');const p=card.querySelector('.issue-location')||card.querySelector('p');p&&(p.textContent=issue.locationLabel||'Pinned location');const metrics=$$('.issue-metrics strong',card);if(metrics[0])metrics[0].textContent=issue.upvotes??0;if(metrics[1])metrics[1].textContent=issue.priority??'—';if(metrics[2])metrics[2].textContent=issue.reportCount??1;$('.support-button')?.setAttribute('data-issue-id',issue.id||'')});
 window.addEventListener('koinos:error',e=>toast(e.detail?.message||'Something went wrong. Please try again.'));
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal&&!modal.hidden)closeReport(e)});
 ensureLive().then(()=>window.KOINOS_LIVE?.initHomeMap?.()).catch(err=>console.warn('KOINOS live layer delayed:',err));
})();
