/* KOINOS — production UI layer. Live maps/data are provided by live-core.js. */
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
(()=>{
  const toast=(message)=>{const n=$('#toast');if(!n)return;n.textContent=message;n.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>n.classList.remove('show'),2800)};
  const modal=$('#report-modal');let currentStep=1;
  const renderStep=(step)=>{currentStep=step;$$('.report-step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===step));$('#modal-step')&&($('#modal-step').textContent=`0${step} / 04`);$('#modal-progress-bar')&&($('#modal-progress-bar').style.width=`${step*25}%`);if(step===4){$('#ai-loading')&&($('#ai-loading').style.display='block');$('#ai-result')?.classList.remove('show');clearTimeout(window.__ai);window.__ai=setTimeout(()=>{$('#ai-loading')&&($('#ai-loading').style.display='none');$('#ai-result')?.classList.add('show')},700)}};
  const openReport=(e)=>{e?.preventDefault();e?.stopPropagation();if(!modal)return;modal.hidden=false;document.body.style.overflow='hidden';renderStep(1)};
  const closeReport=(e)=>{e?.preventDefault();e?.stopPropagation();if(!modal)return;modal.hidden=true;document.body.style.overflow='';$$('.report-step').forEach(x=>x.classList.remove('active'));$('.report-step[data-step="1"]')?.classList.add('active');$('#modal-success')?.classList.remove('show');};
  // Delegated handling prevents stale/duplicate handlers from turning report buttons into navigation links.
  document.addEventListener('click',(e)=>{const report=e.target.closest?.('.report-trigger');if(report){openReport(e);return}const separate=e.target.closest?.('.separate-button');if(separate){e.preventDefault();e.stopImmediatePropagation();saveReport(true);return}const next=e.target.closest?.('.modal-next');if(next){e.preventDefault();if(currentStep<4)renderStep(currentStep+1);return}const close=e.target.closest?.('.modal-close,.close-success');if(close){closeReport(e);return}if(e.target===modal){closeReport(e)}} ,true);
  const ensureLive=()=>new Promise((resolve,reject)=>{if(window.KOINOS_LIVE?.submitReport)return resolve(window.KOINOS_LIVE);let s=document.querySelector('script[data-koinos-live-core]');if(!s){s=document.createElement('script');s.src=`./live-core.js?v=${Date.now()}`;s.dataset.koinosLiveCore='true';s.async=true;s.onload=()=>window.KOINOS_LIVE?.submitReport?resolve(window.KOINOS_LIVE):reject(Error('Live service failed to initialize'));s.onerror=()=>reject(Error('Could not load live service'));document.head.appendChild(s)}else{s.addEventListener('load',()=>window.KOINOS_LIVE?.submitReport?resolve(window.KOINOS_LIVE):reject(Error('Live service failed to initialize')),{once:true});s.addEventListener('error',reject,{once:true})}});
  async function saveReport(closeAfter=false){try{const live=await ensureLive();const result=await live.submitReport();if(!result){toast('We could not save the report. Check your connection and try again.');return}if(closeAfter){toast('Report saved to KOINOS.');closeReport();return}$$('.report-step').forEach(x=>x.classList.remove('active'));$('#modal-success')?.classList.add('show');toast(result.communityMatch?`Connected with ${result.similarIssues?.length||'nearby'} related report(s).`:'Your report is now part of the community record.')}catch(err){console.error(err);toast('Report service is unavailable. Please try again in a moment.')}}
  const photo=$('#photo-upload');if(photo){photo.accept='image/*';photo.removeAttribute('capture');photo.removeAttribute('capturemode');photo.setAttribute('data-koinos-file-picker','true')}
  document.addEventListener('click',(e)=>{const take=e.target.closest?.('#take-photo');const label=e.target.closest?.('label[for="photo-upload"]');if(take||label){e.preventDefault();e.stopPropagation();photo?.click()}const suggestion=e.target.closest?.('[data-suggestion]');if(suggestion){const input=$('#report-description');if(input){input.value=`${input.value?input.value+' ':''}${suggestion.dataset.suggestion}.`;input.focus()}}},true);
  photo?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')){toast('Please choose an image file.');e.target.value='';return}if(f.size>4*1024*1024){toast('Photo must be under 4 MB.');e.target.value='';return}$('#file-name')&&($('#file-name').textContent=f.name);$('#take-photo')&&($('#take-photo').textContent='Change photo');let p=$('#photo-preview');if(!p){p=document.createElement('img');p.id='photo-preview';p.alt='Selected issue photo';p.style.cssText='display:block;width:100%;max-height:220px;object-fit:cover;border-radius:18px;margin:14px 0 0';photo.parentElement?.appendChild(p)}const r=new FileReader();r.onload=()=>{p.src=r.result;p.hidden=false};r.readAsDataURL(f)});
  document.addEventListener('click',async(e)=>{const support=e.target.closest?.('.support-button');if(support){e.preventDefault();const id=support.dataset.issueId;if(!id){toast('Choose an issue on the map first.');return}const result=await window.KOINOS_LIVE?.upvote(id);if(!result){toast('Could not add your support. Try again.');return}const count=result.upvotes??0;$('#affected-count')&&($('#affected-count').textContent=count);$('.support-note')&&($('.support-note').textContent=`${count} people have confirmed this problem.`);support.dataset.supported='true';support.innerHTML="You're affected too <span>✓</span>";toast('Your voice was added to this community issue.')}const filter=e.target.closest?.('.filter-button');if(filter){$$('.filter-button').forEach(x=>x.classList.remove('active'));filter.classList.add('active');window.KOINOS_LIVE?.filterMap(filter.dataset.filter||'all')}const merge=e.target.closest?.('.merge-button');if(merge){$('.shared-issue')?.classList.add('is-merging');merge.innerHTML='37 reports merged <span>✓</span>';toast('Reports became one shared issue.');setTimeout(()=>$('.shared-issue')?.classList.remove('is-merging'),800)}},false);
  window.addEventListener('koinos:issue',e=>{const issue=e.detail||{},card=$('#selected-issue');if(!card)return;card.querySelector('h3')&&(card.querySelector('h3').textContent=issue.title||'Civic issue');const p=card.querySelector('.issue-location')||card.querySelector('p');p&&(p.textContent=issue.locationLabel||issue.address||'Nearby');const metrics=$$('.issue-metrics strong',card);if(metrics[0])metrics[0].textContent=issue.upvotes??0;if(metrics[1])metrics[1].textContent=issue.priority??'—';if(metrics[2])metrics[2].textContent=issue.reportCount??1;$('.support-button')?.setAttribute('data-issue-id',issue.id||'');$$('.verify-button').forEach(b=>b.dataset.issueId=issue.id||'')});
  window.addEventListener('koinos:error',e=>toast(e.detail?.message||'Something went wrong. Please try again.'));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal&&!modal.hidden)closeReport(e)});
  // One-time cache refresh after a new deployment; avoids old Replit-era JS being reused by Safari.
  if(!sessionStorage.getItem('koinos-cache-v4')){sessionStorage.setItem('koinos-cache-v4','1');if(location.search.indexOf('koinosv=')<0){const u=new URL(location.href);u.searchParams.set('koinosv','4');history.replaceState(null,'',u)}}
})();
