/* KOINOS — live civic layer. No fake location fallback. */
(()=>{
 const API=window.KOINOS_API_BASE||'https://koinos-api-5v03.onrender.com';
 const $=(s,r=document)=>r.querySelector(s);
 const escapeHtml=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const emitError=message=>window.dispatchEvent(new CustomEvent('koinos:error',{detail:{message}}));
 const getDeviceId=()=>{const k='koinos-device-id';let id=localStorage.getItem(k);if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;localStorage.setItem(k,id)}return id};
 let reportLocation=null,reportMap=null,reportMarker=null,reportLocationReady=false;
 function getPosition(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,source:'gps'}),err=>{console.warn('KOINOS geolocation:',err.code,err.message);resolve(null)},{enableHighAccuracy:true,timeout:20000,maximumAge:0});})}
 async function reverseGeocode(p){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${p.lat}&lon=${p.lng}&zoom=18&addressdetails=1`,{headers:{Accept:'application/json','Accept-Language':'en'}});if(!r.ok)throw Error();const x=await r.json(),a=x.address||{};return[a.road||a.pedestrian||a.neighbourhood||a.suburb,a.suburb||a.city_district,a.city||a.town||a.village,a.state].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).slice(0,3).join(', ')||'Pinned location'}catch{return 'Pinned location'}}
 async function searchPlace(q){if(!q.trim())return[];try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&addressdetails=1&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json','Accept-Language':'en'}});return r.ok?await r.json():[]}catch{return[]}}
 const loadLeaflet=()=>new Promise((resolve,reject)=>{if(window.L)return resolve(window.L);if(!document.querySelector('[data-koinos-leaflet-css]')){const c=document.createElement('link');c.rel='stylesheet';c.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';c.dataset.koinosLeafletCss='true';document.head.appendChild(c)}const old=document.querySelector('[data-koinos-leaflet-js]');if(old){old.addEventListener('load',()=>window.L?resolve(window.L):reject(Error('Leaflet unavailable')),{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.koinosLeafletJs='true';s.onload=()=>window.L?resolve(window.L):reject(Error('Leaflet unavailable'));s.onerror=()=>reject(Error('Could not load map'));document.head.appendChild(s)});
 async function loadIssues(p){try{const qs=p?`?lat=${encodeURIComponent(p.lat)}&lng=${encodeURIComponent(p.lng)}&radiusKm=12`:'?radiusKm=12';const r=await fetch(`${API}/api/issues${qs}`,{headers:{Accept:'application/json'},cache:'no-store'});const text=await r.text();let x={};try{x=JSON.parse(text)}catch{}if(!r.ok)throw Error(x.error||`Civic data request failed (${r.status})`);return Array.isArray(x)?x:[]}catch(e){console.error('KOINOS issue load:',e);emitError(e.message||'Live civic data could not be loaded.');return[]}}
 function markerIcon(L,sev='low'){return L.divIcon({className:'koinos-live-marker',html:`<span data-severity="${escapeHtml(sev)}"></span>`,iconSize:[28,28],iconAnchor:[14,14]})}
 function renderEmpty(el){const note=document.createElement('div');note.className='koinos-map-empty';note.innerHTML='<strong>No reported issues here yet.</strong><span>Be the first person to report a local problem.</span>';el.appendChild(note)}
 async function initRealMap(){const el=$('#big-map');if(!el||el.dataset.koinosRealMap)return;el.dataset.koinosRealMap='true';try{const L=await loadLeaflet();el.innerHTML='';el.classList.add('koinos-real-map');const p=await getPosition();const center=p||{lat:20.5937,lng:78.9629};const zoom=p?15:5;const map=L.map(el,{zoomControl:false,scrollWheelZoom:false}).setView([center.lat,center.lng],zoom);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);if(p)L.circleMarker([p.lat,p.lng],{radius:8,color:'#22231f',weight:3,fillColor:'#d9ff2f',fillOpacity:1}).addTo(map).bindPopup('Your current location');const issues=await loadIssues(p),markers=[];issues.forEach(issue=>{const lat=Number(issue.latitude),lng=Number(issue.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;const m=L.marker([lat,lng],{icon:markerIcon(L,issue.severity)}).addTo(map);m.bindPopup(`<strong>${escapeHtml(issue.title||'Civic issue')}</strong><br>${escapeHtml(issue.locationLabel||'Pinned location')}<br><b>${Number(issue.upvotes||0)}</b> supporters`);m.on('click',()=>window.dispatchEvent(new CustomEvent('koinos:issue',{detail:issue})));m.__issue=issue;markers.push(m)});if(!markers.length)renderEmpty(el);window.KOINOS_MAP={map,markers,issues,position:p};const loc=$('[data-koinos-location]');if(loc)loc.textContent=p?'Using your GPS location':'Location not shared — showing India overview';const heading=$('.issue-panel-heading span');if(heading)heading.textContent=`${issues.length} issue${issues.length===1?'':'s'} ${p?'near you':'on the map'}`;setTimeout(()=>map.invalidateSize(),200)}catch(e){console.error(e);el.innerHTML='<div class="koinos-map-empty"><strong>Map unavailable right now.</strong><span>Check your connection and reload.</span></div>'}}
 function setReportLocation(p,label){if(!p||!Number.isFinite(Number(p.lat))||!Number.isFinite(Number(p.lng)))return;reportLocation={...p,lat:Number(p.lat),lng:Number(p.lng),locationLabel:label||'Pinned location'};reportLocationReady=true;const name=$('#report-location-name'),sub=$('#report-location-sub');if(name)name.textContent=reportLocation.locationLabel;if(sub)sub.textContent=`${reportLocation.lat.toFixed(5)}, ${reportLocation.lng.toFixed(5)}${reportLocation.accuracy?` · ±${Math.round(reportLocation.accuracy)}m`:''}`;if(reportMarker){reportMarker.setLatLng([reportLocation.lat,reportLocation.lng]);reportMap?.setView([reportLocation.lat,reportLocation.lng],17)}}
 async function selectReportPoint(latlng){const p={lat:Number(latlng.lat),lng:Number(latlng.lng),accuracy:null,source:'pin'};setReportLocation(p,'Finding address…');setReportLocation(p,await reverseGeocode(p))}
 async function initReportLocation(){const host=$('.report-step[data-step="2"] .mini-map');if(!host||host.dataset.koinosReady)return;host.dataset.koinosReady='true';host.innerHTML=`<div class="koinos-location-map" id="report-location-map"></div><div class="koinos-location-tools"><input id="location-search" type="search" autocomplete="off" placeholder="Search any road, landmark or area"><button id="use-my-location" type="button">⌖ Use my location</button></div><div id="location-results" class="koinos-location-results" hidden></div><p class="koinos-location-help">Drag the pin or tap the map to choose the exact spot.</p>`;try{const L=await loadLeaflet();const gps=await getPosition();const center=gps||{lat:20.5937,lng:78.9629};reportMap=L.map($('#report-location-map'),{zoomControl:true}).setView([center.lat,center.lng],gps?17:5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(reportMap);reportMarker=L.marker([center.lat,center.lng],{draggable:true}).addTo(reportMap);reportMarker.on('dragend',()=>selectReportPoint(reportMarker.getLatLng()));reportMap.on('click',e=>selectReportPoint(e.latlng));if(gps)setReportLocation(gps,await reverseGeocode(gps));else{const name=$('#report-location-name'),sub=$('#report-location-sub');if(name)name.textContent='Choose the exact spot';if(sub)sub.textContent='Allow location or search/tap the map';}const search=$('#location-search'),results=$('#location-results');search?.addEventListener('input',()=>{clearTimeout(window.__locationSearch);window.__locationSearch=setTimeout(async()=>{const rows=await searchPlace(search.value);results.innerHTML=rows.map((x,i)=>`<button type="button" data-location-index="${i}">${escapeHtml(x.display_name)}</button>`).join('');results.hidden=!rows.length;results.__rows=rows},400)});results?.addEventListener('click',e=>{const b=e.target.closest('[data-location-index]');if(!b)return;const x=(results.__rows||[])[Number(b.dataset.locationIndex)];if(!x)return;results.hidden=true;search.value=x.display_name;const p={lat:Number(x.lat),lng:Number(x.lon),accuracy:null,source:'search'};reportMap.setView([p.lat,p.lng],17);setReportLocation(p,await reverseGeocode(p))});$('#use-my-location')?.addEventListener('click',async()=>{const p=await getPosition();if(!p){emitError('KOINOS cannot access your GPS location. Enable Location Services for this browser, then tap Use my location again. You can also search for the exact place.');return}reportMap.setView([p.lat,p.lng],17);setReportLocation(p,await reverseGeocode(p))});setTimeout(()=>reportMap.invalidateSize(),200)}catch(e){console.error(e);emitError('Could not load the location map. Please reload and try again.')}}
 async function confirmLocation(){if(!reportLocationReady){emitError('Choose the exact spot on the map before continuing.');return false}return true}
 const fileToDataUrl=f=>new Promise(resolve=>{if(!f||!f.type.startsWith('image/')||f.size>8*1024*1024)return resolve(null);const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>resolve(null);r.readAsDataURL(f)});
 async function submitReport(){const description=$('#report-description')?.value?.trim()||'';if(!description){emitError('Add a short description before submitting.');return null}if(!reportLocationReady){emitError('Choose the exact location before submitting.');return null}const file=$('#photo-upload')?.files?.[0],photoUrl=await fileToDataUrl(file);if(file&&!photoUrl){emitError('That photo could not be prepared. Choose an image under 8 MB.');return null}const payload={title:description.slice(0,70),description,category:$('#report-category')?.value||'other',latitude:reportLocation.lat,longitude:reportLocation.lng,locationLabel:reportLocation.locationLabel,anonymous:Boolean($('#anonymous-toggle')?.checked),photoUrl};try{const r=await fetch(`${API}/api/issues`,{method:'POST',headers:{'Content-Type':'application/json','X-Device-ID':getDeviceId(),Accept:'application/json'},body:JSON.stringify(payload)});const text=await r.text();let body={};try{body=JSON.parse(text)}catch{}if(!r.ok)throw Error(body.error||`Could not save report (${r.status})`);window.dispatchEvent(new CustomEvent('koinos:created',{detail:{...body,photoName:file?.name||null}}));return body}catch(e){console.error('KOINOS submit:',e);emitError(e.message||'Could not save report');return null}}
 async function refreshAfterCreate(issue){if(!window.KOINOS_MAP?.map)return;const p=window.KOINOS_MAP.position;const issues=await loadIssues(p);window.KOINOS_MAP.issues=issues;window.KOINOS_MAP.markers.forEach(m=>m.remove());window.KOINOS_MAP.markers=[];const L=window.L;issues.forEach(i=>{const lat=Number(i.latitude),lng=Number(i.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;const m=L.marker([lat,lng],{icon:markerIcon(L,i.severity)}).addTo(window.KOINOS_MAP.map);m.__issue=i;m.bindPopup(`<strong>${escapeHtml(i.title||'Civic issue')}</strong><br>${escapeHtml(i.locationLabel||'Pinned location')}`);m.on('click',()=>window.dispatchEvent(new CustomEvent('koinos:issue',{detail:i})));window.KOINOS_MAP.markers.push(m)});if(issue&&Number.isFinite(Number(issue.latitude)))window.KOINOS_MAP.map.setView([Number(issue.latitude),Number(issue.longitude)],17)}
 async function upvote(id){if(!id)return null;try{const r=await fetch(`${API}/api/issues/${encodeURIComponent(id)}/upvote`,{method:'POST',headers:{'X-Device-ID':getDeviceId(),Accept:'application/json'}});const b=await r.json().catch(()=>null);return r.ok||r.status===409?b:null}catch{return null}}
 async function verify(id,verdict){if(!id)return null;try{const r=await fetch(`${API}/api/issues/${encodeURIComponent(id)}/verify`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({verdict})});return r.ok?await r.json():null}catch{return null}}
 function filterMap(category='all'){(window.KOINOS_MAP?.markers||[]).forEach(m=>m.setOpacity(category==='all'||m.__issue?.category===category?1:.15))}
 function setupPhotoUpload(){const photo=$('#photo-upload');if(!photo)return;photo.accept='image/*';photo.removeAttribute('capture');photo.removeAttribute('capturemode');photo.addEventListener('change',()=>{const f=photo.files?.[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>8*1024*1024){emitError('Please choose an image under 8 MB.');photo.value='';return}const fn=$('#file-name');if(fn)fn.textContent=f.name;const take=$('#take-photo');if(take)take.textContent='Change photo';let preview=$('#photo-preview');if(!preview){preview=document.createElement('img');preview.id='photo-preview';preview.alt='Selected issue photo';preview.style.cssText='display:block;width:100%;max-height:220px;object-fit:cover;border-radius:18px;margin-top:14px';photo.parentElement?.appendChild(preview)}const r=new FileReader();r.onload=()=>{preview.src=r.result;preview.hidden=false};r.readAsDataURL(f)})}
 window.KOINOS_LIVE={submitReport,upvote,verify,getPosition,reverseGeocode,initRealMap,initReportLocation,confirmLocation,filterMap,refreshAfterCreate,apiBase:API,deviceId:getDeviceId};
 const boot=()=>{setupPhotoUpload();initRealMap()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.addEventListener('koinos:report-open',()=>setTimeout(initReportLocation,100));window.addEventListener('koinos:created',e=>refreshAfterCreate(e.detail));
})();
