/* KOINOS — live civic layer: real OpenStreetMap + PostgreSQL-backed civic data. */
(()=>{
 const API=window.KOINOS_API_BASE||'https://koinos-api-5v03.onrender.com';
 const $=(s,r=document)=>r.querySelector(s);
 const escapeHtml=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const getDeviceId=()=>{const k='koinos-device-id';let id=localStorage.getItem(k);if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;localStorage.setItem(k,id)}return id};
 let reportLocation=null, reportMap=null, reportMarker=null, reportLocationReady=false;
 const emitError=message=>window.dispatchEvent(new CustomEvent('koinos:error',{detail:{message}}));
 const getPosition=()=>new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,source:'gps'}),()=>resolve(null),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})});
 async function reverseGeocode(p){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${p.lat}&lon=${p.lng}&zoom=18&addressdetails=1`,{headers:{Accept:'application/json','Accept-Language':'en'}});if(!r.ok)throw Error();const x=await r.json(),a=x.address||{};return[a.road||a.pedestrian||a.neighbourhood,a.suburb||a.city_district,a.city||a.town||a.village].filter(Boolean).slice(0,3).join(', ')||'Pinned location'}catch{return 'Pinned location'}}
 async function searchPlace(q){if(!q.trim())return[];try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=in&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json','Accept-Language':'en'}});return r.ok?await r.json():[]}catch{return[]}}
 const loadLeaflet=()=>new Promise((resolve,reject)=>{if(window.L)return resolve(window.L);if(!document.querySelector('[data-koinos-leaflet-css]')){const c=document.createElement('link');c.rel='stylesheet';c.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';c.dataset.koinosLeafletCss='true';document.head.appendChild(c)}const old=document.querySelector('[data-koinos-leaflet-js]');if(old){old.addEventListener('load',()=>resolve(window.L),{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.koinosLeafletJs='true';s.onload=()=>resolve(window.L);s.onerror=reject;document.head.appendChild(s)});
 const icon=(L,s='low')=>L.divIcon({className:'koinos-live-marker',html:`<span data-severity="${escapeHtml(s)}"></span>`,iconSize:[28,28],iconAnchor:[14,14]});
 async function loadIssues(p){try{const url=p?`${API}/api/issues?lat=${p.lat}&lng=${p.lng}&radiusKm=12`:`${API}/api/issues?radiusKm=12`;const r=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error();const x=await r.json();return Array.isArray(x)?x:[]}catch{emitError('Live civic data could not be loaded. Check the KOINOS API.');return[]}}
 function renderEmpty(el){if(!el)return;const note=document.createElement('div');note.className='koinos-map-empty';note.innerHTML='<strong>No reported issues nearby yet.</strong><span>Be the first to make a local problem visible.</span>';el.appendChild(note)}
 async function initRealMap(){const el=$('#big-map');if(!el)return;try{const L=await loadLeaflet();el.innerHTML='';el.classList.add('koinos-real-map');const p=await getPosition()||{lat:12.9716,lng:77.5946,accuracy:null,source:'default'};const map=L.map(el,{zoomControl:false,scrollWheelZoom:false}).setView([p.lat,p.lng],14);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);if(p.source==='gps')L.circleMarker([p.lat,p.lng],{radius:7,color:'#22231f',weight:3,fillColor:'#d9ff2f',fillOpacity:1}).addTo(map).bindPopup('You are here');const issues=await loadIssues(p),markers=[];issues.forEach(issue=>{if(!Number.isFinite(Number(issue.latitude))||!Number.isFinite(Number(issue.longitude)))return;const m=L.marker([Number(issue.latitude),Number(issue.longitude)],{icon:icon(L,issue.severity||'low')}).addTo(map);m.bindPopup(`<strong>${escapeHtml(issue.title||'Civic issue')}</strong><br>${escapeHtml(issue.locationLabel||'Nearby')}<br><b>${issue.upvotes||0}</b> people affected`);m.on('click',()=>window.dispatchEvent(new CustomEvent('koinos:issue',{detail:issue})));m.__issue=issue;markers.push(m)});if(!markers.length)renderEmpty(el);window.KOINOS_MAP={map,markers,issues,position:p};const loc=$('[data-koinos-location]');if(loc)loc.textContent=p.source==='gps'?'Using your location':'Showing Bengaluru';const heading=$('.issue-panel-heading span');if(heading)heading.textContent=`${issues.length} issue${issues.length===1?'':'s'} near you`;setTimeout(()=>map.invalidateSize(),150)}catch(e){console.warn('KOINOS map error',e)}}
 function setReportLocation(p,label){reportLocation={...p,locationLabel:label||'Pinned location'};reportLocationReady=true;const name=$('#report-location-name'),sub=$('#report-location-sub');if(name)name.textContent=reportLocation.locationLabel;if(sub)sub.textContent=`${reportLocation.lat.toFixed(5)}, ${reportLocation.lng.toFixed(5)}${reportLocation.accuracy?` · ±${Math.round(reportLocation.accuracy)}m`:''}`;if(reportMarker){reportMarker.setLatLng([p.lat,p.lng]);reportMap?.setView([p.lat,p.lng],17)}}
 async function selectReportPoint(latlng){const p={lat:Number(latlng.lat),lng:Number(latlng.lng),accuracy:null,source:'pin'};setReportLocation(p,'Finding address…');const label=await reverseGeocode(p);setReportLocation(p,label)}
 async function initReportLocation(){const host=$('.report-step[data-step="2"] .mini-map');if(!host||host.dataset.koinosReady)return;host.dataset.koinosReady='true';host.innerHTML=`<div id="report-location-map" style="height:240px;border-radius:20px;overflow:hidden"></div><div style="display:flex;gap:8px;margin:10px 0"><input id="location-search" type="search" placeholder="Search a road, landmark or area" style="flex:1;min-width:0;padding:13px 14px;border:1px solid #ddd;border-radius:14px;font:inherit;background:#fff"><button id="use-my-location" type="button" style="padding:13px 15px;border:1px solid #ddd;border-radius:14px;background:#fff;font-weight:700">Use my location</button></div><div id="location-results" style="display:none;position:relative;z-index:1000;background:#fff;border:1px solid #ddd;border-radius:14px;overflow:hidden"></div>`;const L=await loadLeaflet();const gps=await getPosition();const center=gps||{lat:12.9716,lng:77.5946};reportMap=L.map($('#report-location-map'),{zoomControl:true}).setView([center.lat,center.lng],gps?17:12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(reportMap);reportMarker=L.marker([center.lat,center.lng],{draggable:true}).addTo(reportMap);reportMarker.on('dragend',()=>selectReportPoint(reportMarker.getLatLng()));reportMap.on('click',e=>selectReportPoint(e.latlng));if(gps){setReportLocation(gps,'Finding address…');setReportLocation(gps,await reverseGeocode(gps));}else{const name=$('#report-location-name');if(name)name.textContent='Choose the exact spot';const sub=$('#report-location-sub');if(sub)sub.textContent='Search or tap the map to place the pin';}const search=$('#location-search'),results=$('#location-results');search?.addEventListener('input',()=>{clearTimeout(window.__locationSearch);window.__locationSearch=setTimeout(async()=>{const rows=await searchPlace(search.value);results.innerHTML=rows.map((x,i)=>`<button type="button" data-location-index="${i}" style="display:block;width:100%;padding:12px 14px;text-align:left;border:0;border-bottom:1px solid #eee;background:#fff">${escapeHtml(x.display_name)}</button>`).join('');results.style.display=rows.length?'block':'none';results.__rows=rows},350)});results?.addEventListener('click',e=>{const b=e.target.closest('[data-location-index]'),rows=results.__rows||[];if(!b)return;const x=rows[Number(b.dataset.locationIndex)];results.style.display='none';search.value=x.display_name;reportMap.setView([Number(x.lat),Number(x.lon)],17);selectReportPoint({lat:Number(x.lat),lng:Number(x.lon)})});$('#use-my-location')?.addEventListener('click',async()=>{const p=await getPosition();if(!p)return emitError('Location access is off. Allow location in Safari or search for the place instead.');reportMap.setView([p.lat,p.lng],17);setReportLocation(p,await reverseGeocode(p))});setTimeout(()=>reportMap.invalidateSize(),200)}
 async function confirmLocation(){if(!reportLocationReady){emitError('Choose the exact location on the map before continuing.');return false}return true}
 const fileToDataUrl=f=>new Promise(resolve=>{if(!f||!f.type.startsWith('image/')||f.size>8*1024*1024)return resolve(null);const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>resolve(null);r.readAsDataURL(f)});
 async function submitReport(){const description=$('#report-description')?.value?.trim()||'';if(!description){emitError('Add a short description before submitting.');return null}if(!reportLocationReady){emitError('Choose the exact location before submitting.');return null}const file=$('#photo-upload')?.files?.[0],photoUrl=await fileToDataUrl(file);const payload={title:description.slice(0,70),description,category:$('#report-category')?.value||'other',latitude:reportLocation.lat,longitude:reportLocation.lng,locationLabel:reportLocation.locationLabel,anonymous:Boolean($('#anonymous-toggle')?.checked),photoUrl};try{const r=await fetch(`${API}/api/issues`,{method:'POST',headers:{'Content-Type':'application/json','X-Device-ID':getDeviceId()},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||`Could not save report (HTTP ${r.status})`);window.dispatchEvent(new CustomEvent('koinos:created',{detail:{...body,photoName:file?.name||null}}));return body}catch(e){console.error('KOINOS report submit failed',e);emitError(e.message||'Could not save report');return null}}
 async function upvote(id){if(!id)return null;try{const r=await fetch(`${API}/api/issues/${encodeURIComponent(id)}/upvote`,{method:'POST',headers:{'X-Device-ID':getDeviceId(),Accept:'application/json'}});const body=await r.json().catch(()=>({}));return r.ok||r.status===409?body:null}catch{return null}}
 async function verify(id,verdict){if(!id)return null;try{const r=await fetch(`${API}/api/issues/${encodeURIComponent(id)}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({verdict})});return r.ok?await r.json():null}catch{return null}}
 function filterMap(category='all'){(window.KOINOS_MAP?.markers||[]).forEach(m=>{const match=category==='all'||m.__issue?.category===category;m.setOpacity(match?1:.15)})}
 function setupPhotoUpload(){const photo=$('#photo-upload');if(!photo)return;photo.accept='image/*';photo.removeAttribute('capture');photo.removeAttribute('capturemode');const label=document.querySelector('label[for="photo-upload"]');label?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();photo.click()});photo.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')){emitError('Please choose an image file.');photo.value='';return}if(f.size>8*1024*1024){emitError('Photo is too large. Choose an image under 8 MB.');photo.value='';return}$('#file-name')&&($('#file-name').textContent=f.name);$('#take-photo')&&($('#take-photo').textContent='Change photo');let preview=$('#photo-preview');if(!preview){preview=document.createElement('img');preview.id='photo-preview';preview.alt='Selected issue photo';preview.style.cssText='display:block;width:100%;max-height:220px;object-fit:cover;border-radius:18px;margin:14px 0 0';photo.parentElement?.appendChild(preview)}const r=new FileReader();r.onload=()=>{preview.src=r.result;preview.hidden=false};r.readAsDataURL(f)})}
 window.KOINOS_LIVE={submitReport,upvote,verify,getPosition,reverseGeocode,initRealMap,initReportLocation,confirmLocation,filterMap,apiBase:API,deviceId:getDeviceId};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setupPhotoUpload();initRealMap()});else{setupPhotoUpload();initRealMap()}
 window.addEventListener('koinos:report-open',()=>setTimeout(initReportLocation,50));
})();
