/* KOINOS — real civic layer: GPS + OpenStreetMap + PostgreSQL API. */
(()=>{
 const API=window.KOINOS_API_BASE||'https://koinos-api-5v03.onrender.com';
 const $=(s,r=document)=>r.querySelector(s);
 const esc=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const error=message=>window.dispatchEvent(new CustomEvent('koinos:error',{detail:{message}}));
 const device=()=>{let id=localStorage.getItem('koinos-device-id');if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;localStorage.setItem('koinos-device-id',id)}return id};
 const position=()=>new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,source:'gps'}),()=>resolve(null),{enableHighAccuracy:true,timeout:20000,maximumAge:0})});
 async function reverse(p){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${p.lat}&lon=${p.lng}&zoom=18&addressdetails=1`,{headers:{Accept:'application/json','Accept-Language':'en'}});if(!r.ok)throw 0;const x=await r.json(),a=x.address||{};return[a.road||a.pedestrian,a.neighbourhood||a.suburb,a.city||a.town||a.village,a.state].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).slice(0,3).join(', ')||'Pinned location'}catch{return 'Pinned location'}}
 async function search(q){try{if(!q.trim())return[];const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&addressdetails=1&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json','Accept-Language':'en'}});return r.ok?await r.json():[]}catch{return[]}}
 const leaflet=()=>new Promise((resolve,reject)=>{if(window.L)return resolve(window.L);if(!document.querySelector('[data-koinos-leaflet-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.koinosLeafletCss='1';document.head.appendChild(l)}const old=document.querySelector('[data-koinos-leaflet-js]');if(old){old.addEventListener('load',()=>window.L?resolve(window.L):reject(Error('Map unavailable')),{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.koinosLeafletJs='1';s.onload=()=>window.L?resolve(window.L):reject(Error('Map unavailable'));s.onerror=()=>reject(Error('Map unavailable'));document.head.appendChild(s)});
 let maps={};
 async function getIssues(p){try{const qs=p?`?lat=${p.lat}&lng=${p.lng}&radiusKm=25`:'?radiusKm=100';const r=await fetch(`${API}/api/issues${qs}`,{cache:'no-store',headers:{Accept:'application/json'}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||`Civic data request failed (${r.status})`);return Array.isArray(b)?b:[]}catch(e){console.error(e);error(e.message||'Could not load live civic data');return[]}}
 const icon=(L,sev)=>L.divIcon({className:'koinos-live-marker',html:`<span data-severity="${esc(sev||'low')}"></span>`,iconSize:[28,28],iconAnchor:[14,14]});
 function addMarkers(L,map,issues){const markers=[];issues.forEach(i=>{const lat=Number(i.latitude),lng=Number(i.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;const m=L.marker([lat,lng],{icon:icon(L,i.severity)}).addTo(map);m.__issue=i;m.bindPopup(`<strong>${esc(i.title||'Civic issue')}</strong><br>${esc(i.locationLabel||'Pinned location')}<br><b>${i.upvotes||0}</b> supporters`);m.on('click',()=>window.dispatchEvent(new CustomEvent('koinos:issue',{detail:i})));markers.push(m)});return markers}
 async function initHomeMap(){const host=$('.hero-visual');if(!host||host.dataset.koinosHomeMap)return;host.dataset.koinosHomeMap='1';try{const L=await leaflet(),p=await position();host.innerHTML='<div class="koinos-home-map" id="koinos-home-map"></div><div class="koinos-map-status" id="koinos-home-status">Locating you…</div>';const center=p||{lat:20.5937,lng:78.9629},map=L.map($('#koinos-home-map'),{zoomControl:false,scrollWheelZoom:false}).setView([center.lat,center.lng],p?15:5);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);if(p)L.circleMarker([p.lat,p.lng],{radius:9,weight:3,fillOpacity:1}).addTo(map).bindPopup('Your current location');const issues=await getIssues(p);const markers=addMarkers(L,map,issues);const st=$('#koinos-home-status');if(st)st.textContent=p?'● Live location · civic issues nearby':'Location not shared · showing national view';maps.home={map,markers,issues,position:p};setTimeout(()=>map.invalidateSize(),300)}catch(e){console.error(e);host.innerHTML='<div class="koinos-map-empty"><strong>Live map unavailable.</strong><span>Please check your connection and reload.</span></div>'}}
 async function initRealMap(){const host=$('#big-map');if(!host||host.dataset.koinosRealMap)return;host.dataset.koinosRealMap='1';try{const L=await leaflet(),p=await position();host.innerHTML='<div class="koinos-explore-map" id="koinos-explore-map"></div><div class="koinos-map-status" id="koinos-explore-status">Locating you…</div>';const center=p||{lat:20.5937,lng:78.9629},map=L.map(host,{zoomControl:true}).setView([center.lat,center.lng],p?15:5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);if(p)L.circleMarker([p.lat,p.lng],{radius:9,weight:3,fillOpacity:1}).addTo(map).bindPopup('Your current location');const issues=await getIssues(p),markers=addMarkers(L,map,issues);const st=$('#koinos-explore-status');if(st)st.textContent=p?'● Live location':'Location not shared';maps.explore={map,markers,issues,position:p};setTimeout(()=>map.invalidateSize(),300)}catch(e){console.error(e);host.innerHTML='<div class="koinos-map-empty"><strong>Map unavailable.</strong><span>Check your connection and reload.</span></div>'}}
 let report={ready:false,map:null,marker:null,point:null};
 function setPoint(p,label){if(!p)return;report.point={...p,lat:Number(p.lat),lng:Number(p.lng),locationLabel:label||'Pinned location'};report.ready=true;const n=$('#report-location-name'),s=$('#report-location-sub');if(n)n.textContent=report.point.locationLabel;if(s)s.textContent=`${report.point.lat.toFixed(5)}, ${report.point.lng.toFixed(5)}${report.point.accuracy?` · ±${Math.round(report.point.accuracy)}m`:''}`;if(report.marker){report.marker.setLatLng([report.point.lat,report.point.lng]);report.map?.setView([report.point.lat,report.point.lng],17)}}
 async function choose(latlng){const p={lat:Number(latlng.lat),lng:Number(latlng.lng),accuracy:null,source:'pin'};setPoint(p,'Finding address…');setPoint(p,await reverse(p))}
 async function initReportLocation(){const host=$('.report-step[data-step="2"] .mini-map');if(!host||host.dataset.ready)return;host.dataset.ready='1';host.innerHTML='<div class="koinos-location-map" id="report-location-map"></div><div class="koinos-location-tools"><input id="location-search" type="search" placeholder="Search a road, landmark or area" autocomplete="off"><button id="use-my-location" type="button">⌖ Use my location</button></div><div id="location-results" class="koinos-location-results" hidden></div><p class="koinos-location-help">Tap the map or drag the pin to the exact spot.</p>';try{const L=await leaflet(),p=await position(),c=p||{lat:20.5937,lng:78.9629};report.map=L.map($('#report-location-map'),{zoomControl:true}).setView([c.lat,c.lng],p?17:5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(report.map);report.marker=L.marker([c.lat,c.lng],{draggable:true}).addTo(report.map);report.marker.on('dragend',()=>choose(report.marker.getLatLng()));report.map.on('click',e=>choose(e.latlng));if(p)setPoint(p,await reverse(p));else{const n=$('#report-location-name'),s=$('#report-location-sub');if(n)n.textContent='Choose the exact spot';if(s)s.textContent='Allow location or search/tap the map'}const input=$('#location-search'),results=$('#location-results');input?.addEventListener('input',()=>{clearTimeout(window.__loc);window.__loc=setTimeout(async()=>{const rows=await search(input.value);results.innerHTML=rows.map((x,i)=>`<button type="button" data-i="${i}">${esc(x.display_name)}</button>`).join('');results.__rows=rows;results.hidden=!rows.length},450)});results?.addEventListener('click',e=>{const b=e.target.closest('[data-i]');if(!b)return;const x=results.__rows?.[Number(b.dataset.i)];if(!x)return;results.hidden=true;const p={lat:Number(x.lat),lng:Number(x.lon),accuracy:null,source:'search'};report.map.setView([p.lat,p.lng],17);report.marker.setLatLng([p.lat,p.lng]);setPoint(p, x.display_name)});$('#use-my-location')?.addEventListener('click',async()=>{const x=await position();if(!x){error('Location access is unavailable. Enable Location Services for Safari and try again, or search for the exact place.');return}report.map.setView([x.lat,x.lng],17);report.marker.setLatLng([x.lat,x.lng]);setPoint(x,await reverse(x))});setTimeout(()=>report.map.invalidateSize(),250)}catch(e){console.error(e);error('Could not load the location map. Please reload.')}}
 async function confirmLocation(){if(!report.ready){error('Choose the exact location before continuing.');return false}return true}
 const readFile=f=>new Promise(resolve=>{if(!f||!f.type?.startsWith('image/')||f.size>5*1024*1024)return resolve(null);const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>resolve(null);r.readAsDataURL(f)});
 function setupPhoto(){const input=$('#photo-upload');if(!input)return;input.accept='image/*';input.removeAttribute('capture');input.removeAttribute('capturemode');input.addEventListener('change',()=>{const f=input.files?.[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>5*1024*1024){input.value='';error('Please choose an image under 5 MB.');return}const name=$('#file-name');if(name)name.textContent=f.name;let img=$('#photo-preview');if(!img){img=document.createElement('img');img.id='photo-preview';img.alt='Selected issue photo';img.style.cssText='display:block;width:100%;max-height:220px;object-fit:cover;border-radius:18px;margin-top:14px';input.parentElement?.appendChild(img)}const r=new FileReader();r.onload=()=>{img.src=r.result;img.hidden=false};r.readAsDataURL(f);})}
 async function submitReport(){const description=$('#report-description')?.value?.trim()||'';if(!description){error('Add a short description before submitting.');return null}if(!report.ready){error('Choose the exact location before submitting.');return null}const f=$('#photo-upload')?.files?.[0],photoUrl=await readFile(f);if(f&&!photoUrl){error('Photo must be an image under 5 MB.');return null}const payload={title:description.slice(0,70),description,category:$('#report-category')?.value||'other',latitude:report.point.lat,longitude:report.point.lng,locationLabel:report.point.locationLabel,anonymous:Boolean($('#anonymous-toggle')?.checked),photoUrl};try{const r=await fetch(`${API}/api/issues`,{method:'POST',headers:{'Content-Type':'application/json','X-Device-ID':device(),Accept:'application/json'},body:JSON.stringify(payload)});const text=await r.text();let b={};try{b=JSON.parse(text)}catch{}if(!r.ok)throw Error(b.error||`Could not save report (${r.status})`);window.dispatchEvent(new CustomEvent('koinos:created',{detail:b}));return b}catch(e){console.error('KOINOS submit',e);error(e.message||'Could not save report');return null}}
 async function refresh(issue){for(const key of ['home','explore']){const m=maps[key];if(!m)continue;const issues=await getIssues(m.position);m.issues=issues;m.markers.forEach(x=>x.remove());m.markers=addMarkers(window.L,m.map,issues);if(issue?.latitude&&key==='home')m.map.setView([Number(issue.latitude),Number(issue.longitude)],17)}}
 async function upvote(id){try{const r=await fetch(`${API}/api/issues/${encodeURIComponent(id)}/upvote`,{method:'POST',headers:{'X-Device-ID':device(),Accept:'application/json'}});return r.ok||r.status===409?await r.json():null}catch{return null}}
 function filterMap(cat='all'){(maps.explore?.markers||[]).forEach(m=>m.setOpacity(cat==='all'||m.__issue?.category===cat?1:.2))}
 window.KOINOS_LIVE={apiBase:API,getPosition:position,reverseGeocode:reverse,initHomeMap,initRealMap,initReportLocation,confirmLocation,submitReport,refreshAfterCreate:refresh,upvote,filterMap,deviceId:device};
 const boot=()=>{setupPhoto();initHomeMap();initRealMap()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.addEventListener('koinos:report-open',()=>setTimeout(initReportLocation,100));window.addEventListener('koinos:created',e=>refresh(e.detail));
})();
