-- KOINOS core database for the static site.
-- Run this once in Supabase SQL Editor.
-- Safe to re-run.

create table if not exists public.issues (
  id text primary key,
  title text not null,
  category text not null default 'other',
  description text not null default '',
  location_label text,
  latitude double precision,
  longitude double precision,
  photo_url text,
  anonymous boolean not null default false,
  owner_user_id uuid,
  status text not null default 'reported',
  severity text not null default 'low',
  priority integer not null default 0,
  upvotes integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.issues add column if not exists owner_user_id uuid;
alter table public.issues add column if not exists photo_url text;
alter table public.issues add column if not exists anonymous boolean not null default false;
alter table public.issues add column if not exists status text not null default 'reported';
alter table public.issues add column if not exists severity text not null default 'low';
alter table public.issues add column if not exists priority integer not null default 0;
alter table public.issues add column if not exists upvotes integer not null default 0;
alter table public.issues add column if not exists created_at timestamptz not null default now();
alter table public.issues add column if not exists updated_at timestamptz not null default now();

create index if not exists issues_owner_idx on public.issues(owner_user_id);
create index if not exists issues_geo_idx on public.issues(latitude, longitude);
create index if not exists issues_status_idx on public.issues(status);
create index if not exists issues_priority_idx on public.issues(priority desc);

create table if not exists public.issue_events (
  id bigint generated by default as identity primary key,
  issue_id text not null references public.issues(id) on delete cascade,
  status text not null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists issue_events_issue_idx on public.issue_events(issue_id, created_at);

create table if not exists public.issue_votes (
  issue_id text not null references public.issues(id) on delete cascade,
  device_id text not null,
  created_at timestamptz not null default now(),
  primary key(issue_id, device_id)
);

alter table public.issues enable row level security;
alter table public.issue_events enable row level security;
alter table public.issue_votes enable row level security;

drop policy if exists "KOINOS public issue read" on public.issues;
create policy "KOINOS public issue read" on public.issues for select to anon, authenticated using (true);

drop policy if exists "KOINOS issue insert" on public.issues;
create policy "KOINOS issue insert" on public.issues for insert to anon, authenticated with check (
  (anonymous = true and owner_user_id is null)
  or (anonymous = false and owner_user_id = auth.uid())
  or (owner_user_id is null)
);

drop policy if exists "KOINOS public events read" on public.issue_events;
create policy "KOINOS public events read" on public.issue_events for select to anon, authenticated using (true);

drop policy if exists "KOINOS issue event insert" on public.issue_events;
create policy "KOINOS issue event insert" on public.issue_events for insert to anon, authenticated with check (exists (select 1 from public.issues i where i.id = issue_id and (i.owner_user_id = auth.uid() or i.owner_user_id is null)));

drop policy if exists "KOINOS vote insert" on public.issue_votes;
create policy "KOINOS vote insert" on public.issue_votes for insert to anon, authenticated with check (char_length(device_id) between 10 and 120);

create or replace function public.koinos_upvote_issue(p_issue_id text, p_device_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  changed boolean := false;
  item public.issues;
begin
  if p_issue_id is null or p_device_id is null or char_length(p_device_id) < 10 then
    raise exception 'Invalid vote';
  end if;
  insert into public.issue_votes(issue_id, device_id)
  values (p_issue_id, p_device_id)
  on conflict (issue_id, device_id) do nothing;
  if found then
    changed := true;
    update public.issues
      set upvotes = upvotes + 1,
          priority = least(100, priority + 1),
          updated_at = now()
      where id = p_issue_id;
  end if;
  select * into item from public.issues where id = p_issue_id;
  if not found then raise exception 'Issue not found'; end if;
  return jsonb_build_object(
    'id', item.id, 'title', item.title, 'category', item.category,
    'description', item.description, 'locationLabel', item.location_label,
    'latitude', item.latitude, 'longitude', item.longitude,
    'photoUrl', item.photo_url, 'anonymous', item.anonymous,
    'status', item.status, 'severity', item.severity, 'priority', item.priority,
    'upvotes', item.upvotes, 'createdAt', item.created_at, 'updatedAt', item.updated_at,
    'alreadyVoted', not changed
  );
end;
$$;

grant execute on function public.koinos_upvote_issue(text, text) to anon, authenticated;
