-- KOINOS core database for the static site.
-- Run this once in Supabase SQL Editor. Safe to re-run.

create table if not exists public.issues (
  id text primary key, title text not null, category text not null default 'other', description text not null default '',
  location_label text, latitude double precision, longitude double precision, photo_url text,
  anonymous boolean not null default false, owner_user_id uuid, status text not null default 'reported',
  severity text not null default 'low', priority integer not null default 0, upvotes integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.issues add column if not exists owner_user_id uuid;
alter table public.issues add column if not exists photo_url text;
alter table public.issues add column if not exists anonymous boolean not null default false;
alter table public.issues add column if not exists status text not null default 'reported';
alter table public.issues add column if not exists severity text not null default 'low';
alter table public.issues add column if not exists priority integer not null default 0;
alter table public.issues add column if not exists upvotes integer not null default 0;
alter table public.issues add column if not exists created_at timestamptz not null default now();
alter table public.issues add column if not exists updated_at timestamptz not null default now();
create index if not exists issues_owner_idx on public.issues(owner_user_id);
create index if not exists issues_geo_idx on public.issues(latitude, longitude);
create index if not exists issues_status_idx on public.issues(status);
create index if not exists issues_priority_idx on public.issues(priority desc);

create table if not exists public.issue_events (
  id bigint generated by default as identity primary key,
  issue_id text not null references public.issues(id) on delete cascade,
  status text not null, note text, created_at timestamptz not null default now()
);
create index if not exists issue_events_issue_idx on public.issue_events(issue_id, created_at);
create table if not exists public.issue_votes (
  issue_id text not null references public.issues(id) on delete cascade,
  device_id text not null, created_at timestamptz not null default now(), primary key(issue_id, device_id)
);

-- Authority roles. Promote trusted staff by changing profiles.role to 'authority'
-- in Supabase SQL Editor; do not expose role editing to the browser.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'citizen' check (role in ('citizen','authority')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_koinos_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_koinos_auth_user_created on auth.users;
create trigger on_koinos_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_koinos_new_user();

alter table public.profiles enable row level security;
drop policy if exists "KOINOS profile self read" on public.profiles;
create policy "KOINOS profile self read" on public.profiles for select to authenticated using ((select auth.uid()) = id);

grant select on table public.profiles to authenticated;

-- Supabase projects created with the newer Data API settings may require explicit grants.
revoke all on table public.issues, public.issue_events, public.issue_votes from anon, authenticated;
grant select, insert on table public.issues to anon, authenticated;
grant select, insert on table public.issue_events to anon, authenticated;
grant usage, select on sequence public.issue_events_id_seq to anon, authenticated;

alter table public.issues enable row level security;
alter table public.issue_events enable row level security;
alter table public.issue_votes enable row level security;

drop policy if exists "KOINOS public issue read" on public.issues;
create policy "KOINOS public issue read" on public.issues for select to anon, authenticated using (true);
drop policy if exists "KOINOS issue insert" on public.issues;
create policy "KOINOS issue insert" on public.issues for insert to anon, authenticated with check (
  (anonymous = true and owner_user_id is null) or
  (anonymous = false and owner_user_id = auth.uid())
);
drop policy if exists "KOINOS public events read" on public.issue_events;
create policy "KOINOS public events read" on public.issue_events for select to anon, authenticated using (true);
drop policy if exists "KOINOS issue event insert" on public.issue_events;
create policy "KOINOS issue event insert" on public.issue_events for insert to anon, authenticated with check (
  exists (select 1 from public.issues i where i.id = issue_id and (i.owner_user_id = auth.uid() or i.owner_user_id is null))
);

create or replace function public.koinos_upvote_issue(p_issue_id text, p_device_id text)
returns jsonb language plpgsql security definer set search_path = public
as $$
declare changed boolean := false; item public.issues;
begin
  if p_issue_id is null or p_device_id is null or char_length(p_device_id) < 10 then raise exception 'Invalid vote'; end if;
  insert into public.issue_votes(issue_id, device_id) values (p_issue_id, p_device_id) on conflict (issue_id, device_id) do nothing;
  if found then
    changed := true;
    update public.issues set upvotes=upvotes+1, priority=least(100,priority+1), updated_at=now() where id=p_issue_id;
  end if;
  select * into item from public.issues where id=p_issue_id;
  if not found then raise exception 'Issue not found'; end if;
  return jsonb_build_object('id',item.id,'title',item.title,'category',item.category,'description',item.description,
    'locationLabel',item.location_label,'latitude',item.latitude,'longitude',item.longitude,'photoUrl',item.photo_url,
    'anonymous',item.anonymous,'status',item.status,'severity',item.severity,'priority',item.priority,'upvotes',item.upvotes,
    'createdAt',item.created_at,'updatedAt',item.updated_at,'alreadyVoted',not changed);
end; $$;
grant execute on function public.koinos_upvote_issue(text,text) to anon, authenticated;

-- Only an authority can change a civic issue's workflow status.
create or replace function public.koinos_authority_update_issue(p_issue_id text, p_status text, p_note text default '')
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare item public.issues;
begin
  if not exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'authority') then
    raise exception 'Authority access required';
  end if;
  if p_status not in ('reported','in_progress','resolved') then raise exception 'Invalid status'; end if;
  update public.issues
  set status = p_status, updated_at = now()
  where id = p_issue_id
  returning * into item;
  if not found then raise exception 'Issue not found'; end if;
  insert into public.issue_events(issue_id, status, note)
  values (item.id, item.status, nullif(left(coalesce(p_note,''),500),''));
  return jsonb_build_object('id',item.id,'title',item.title,'category',item.category,'description',item.description,
    'locationLabel',item.location_label,'latitude',item.latitude,'longitude',item.longitude,'photoUrl',item.photo_url,
    'anonymous',item.anonymous,'status',item.status,'severity',item.severity,'priority',item.priority,'upvotes',item.upvotes,
    'createdAt',item.created_at,'updatedAt',item.updated_at);
end;
$$;
revoke execute on function public.koinos_authority_update_issue(text,text,text) from public, anon;
grant execute on function public.koinos_authority_update_issue(text,text,text) to authenticated;
