import express from 'express';
import cors from 'cors';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const { Pool }=pg;
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||4000),DATABASE_URL=process.env.DATABASE_URL,ADMIN_KEY=process.env.ADMIN_KEY||'';
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10}):null;
const app=express();app.disable('x-powered-by');app.use(cors({origin:process.env.CORS_ORIGIN?process.env.CORS_ORIGIN.split(',').map(x=>x.trim()):'*'}));app.use(express.json({limit:'16mb'}));
const fallbackFile=path.join(__dirname,'data','issues.json');
const ensureFallback=async()=>{try{await fs.access(fallbackFile)}catch{await fs.mkdir(path.dirname(fallbackFile),{recursive:true});await fs.writeFile(fallbackFile,'[]')}};
const cleanText=(v,max=5000)=>String(v??'').trim().slice(0,max),validNumber=v=>Number.isFinite(Number(v));
const distanceKm=(aLat,aLng,bLat,bLng)=>{if(![aLat,aLng,bLat,bLng].every(validNumber))return Infinity;const r=Math.PI/180,p1=Number(aLat)*r,dp=(Number(bLat)-Number(aLat))*r,dl=(Number(bLng)-Number(aLng))*r,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(Number(bLat)*r)*Math.sin(dl/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const severity=text=>{const t=String(text||'').toLowerCase();if(/school|hospital|accident|injur|fire|flood|collapse|exposed wire|electric shock|danger|unsafe|open manhole|sewer/.test(t))return'high';if(/pothole|leak|overflow|broken|damaged|blocked|garbage|waste|streetlight|drain/.test(t))return'medium';return'low'};
const priority=(sev,votes=0,ageDays=0)=>Math.min(100,(sev==='high'?55:sev==='medium'?40:25)+Math.min(25,Number(votes)||0)+Math.min(10,Math.floor(Number(ageDays)||0))+10);
const normalize=r=>({id:r.id,title:r.title,category:r.category,description:r.description,locationLabel:r.location_label,latitude:r.latitude,longitude:r.longitude,photoUrl:r.photo_url,anonymous:r.anonymous,status:r.status,severity:r.severity,priority:r.priority,upvotes:r.upvotes,createdAt:r.created_at,updatedAt:r.updated_at});
const readFallback=async()=>{await ensureFallback();return JSON.parse(await fs.readFile(fallbackFile,'utf8'))},writeFallback=x=>fs.writeFile(fallbackFile,JSON.stringify(x,null,2));
const authAdmin=(req,res)=>{if(ADMIN_KEY&&req.get('x-admin-key')!==ADMIN_KEY){res.status(401).json({error:'Admin key required'});return false}return true};
const safeDistance=(a,b,c)=>`(6371*acos(GREATEST(-1,LEAST(1,cos(radians(${a}))*cos(radians(latitude))*cos(radians(longitude)-radians(${b}))+sin(radians(${a}))*sin(radians(latitude))))) <= ${c})`;

app.get('/health',async(_q,res)=>{let db=false;if(pool){try{await pool.query('SELECT 1');db=true}catch{}}res.json({ok:true,database:db,mode:db?'postgresql':'fallback',service:'koinos-api',time:new Date().toISOString()})});
app.get('/api/health',async(_q,res)=>{let db=false;if(pool){try{await pool.query('SELECT 1');db=true}catch{}}res.json({ok:true,database:db,mode:db?'postgresql':'fallback',service:'koinos-api',time:new Date().toISOString()})});

app.get('/api/issues',async(req,res)=>{try{const lat=validNumber(req.query.lat)?Number(req.query.lat):null,lng=validNumber(req.query.lng)?Number(req.query.lng):null,radius=Math.min(100,Math.max(.5,Number(req.query.radiusKm)||12)),category=cleanText(req.query.category,30),status=cleanText(req.query.status,30);if(pool){const values=[],where=[];if(lat!==null&&lng!==null){values.push(lat,lng,radius);where.push(`latitude IS NOT NULL AND longitude IS NOT NULL AND ${safeDistance('$1','$2','$3')}`)}if(category&&category!=='all'){values.push(category);where.push(`category=$${values.length}`)}if(status){values.push(status);where.push(`status=$${values.length}`)}const r=await pool.query(`SELECT * FROM issues ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY priority DESC,created_at DESC LIMIT 200`,values);return res.json(r.rows.map(normalize))}let issues=await readFallback();if(lat!==null&&lng!==null)issues=issues.filter(i=>distanceKm(lat,lng,i.latitude,i.longitude)<=radius);if(category&&category!=='all')issues=issues.filter(i=>i.category===category);if(status)issues=issues.filter(i=>i.status===status);res.json(issues.sort((a,b)=>(b.priority||0)-(a.priority||0)).slice(0,200))}catch(e){console.error('GET /api/issues',e);res.status(500).json({error:'Unable to load civic issues'})}});

app.get('/api/issues/:id',async(req,res)=>{try{if(pool){const r=await pool.query('SELECT * FROM issues WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Issue not found'});const e=await pool.query('SELECT status,note,created_at FROM issue_events WHERE issue_id=$1 ORDER BY created_at',[req.params.id]);const b=r.rows[0];let similar=[];if(b.latitude!=null&&b.longitude!=null){const s=await pool.query(`SELECT id,title,category,status,priority,upvotes,latitude,longitude FROM issues WHERE id<>$1 AND latitude IS NOT NULL AND longitude IS NOT NULL AND ${safeDistance('$2','$3','.75')} ORDER BY priority DESC LIMIT 8`,[req.params.id,b.latitude,b.longitude]);similar=s.rows}return res.json({...normalize(b),events:e.rows,similarIssues:similar})}const issues=await readFallback(),i=issues.find(x=>x.id===req.params.id);if(!i)return res.status(404).json({error:'Issue not found'});res.json({...i,events:i.events||[],similarIssues:issues.filter(x=>x.id!==i.id&&distanceKm(i.latitude,i.longitude,x.latitude,x.longitude)<=.75).slice(0,8)})}catch(e){console.error('GET issue',e);res.status(500).json({error:'Unable to load issue'})}});

app.post('/api/issues',async(req,res)=>{try{const b=req.body||{},description=cleanText(b.description,3000),title=cleanText(b.title||description.slice(0,70)||'Civic issue',100);if(!description&&!b.title)return res.status(400).json({error:'A title or description is required'});const lat=validNumber(b.latitude)?Number(b.latitude):null,lng=validNumber(b.longitude)?Number(b.longitude):null;if((lat!==null&&Math.abs(lat)>90)||(lng!==null&&Math.abs(lng)>180))return res.status(400).json({error:'Invalid location coordinates'});const id=crypto.randomUUID(),sev=severity(`${title} ${description}`),p=priority(sev);let similar=[];if(pool&&lat!==null&&lng!==null){const r=await pool.query(`SELECT id,title,category,status,priority,upvotes,latitude,longitude FROM issues WHERE latitude IS NOT NULL AND longitude IS NOT NULL AND status<>'resolved' AND ${safeDistance('$1','$2','.35')} ORDER BY priority DESC LIMIT 8`,[lat,lng]);similar=r.rows}else if(!pool&&lat!==null&&lng!==null){const all=await readFallback();similar=all.filter(x=>x.status!=='resolved'&&distanceKm(lat,lng,x.latitude,x.longitude)<=.35).slice(0,8)}const category=cleanText(b.category,30)||'other',locationLabel=cleanText(b.locationLabel,180)||null,photoUrl=cleanText(b.photoUrl,12000000)||null,anonymous=Boolean(b.anonymous);if(pool){const r=await pool.query(`INSERT INTO issues(id,title,category,description,location_label,latitude,longitude,photo_url,anonymous,status,severity,priority,upvotes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'reported',$10,$11,0) RETURNING *`,[id,title,category,description,locationLabel,lat,lng,photoUrl,anonymous,sev,p]);await pool.query(`INSERT INTO issue_events(issue_id,status,note) VALUES($1,'reported',$2)`,[id,similar.length?`Report received. ${similar.length} nearby active issue(s) may be related.`:'Report received']);return res.status(201).json({...normalize(r.rows[0]),similarIssues:similar,communityMatch:Boolean(similar.length)})}const now=new Date().toISOString(),base={id,title,category,description,locationLabel,latitude:lat,longitude:lng,photoUrl,anonymous,status:'reported',severity:sev,priority:p,upvotes:0,createdAt:now,updatedAt:now};const issues=await readFallback();issues.push({...base,events:[{status:'reported',note:'Report received',createdAt:now}]});await writeFallback(issues);res.status(201).json({...base,similarIssues:similar,communityMatch:Boolean(similar.length)})}catch(e){console.error('POST /api/issues',e);res.status(500).json({error:`Could not save report: ${e?.message||'server error'}`})}});

app.post('/api/issues/:id/upvote',async(req,res)=>{const device=cleanText(req.get('x-device-id'),120);if(!device)return res.status(400).json({error:'X-Device-ID required'});try{if(pool){const v=await pool.query('INSERT INTO issue_votes(issue_id,device_id) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING issue_id',[req.params.id,device]);if(!v.rowCount){const r=await pool.query('SELECT * FROM issues WHERE id=$1',[req.params.id]);return r.rowCount?res.status(409).json({...normalize(r.rows[0]),alreadyVoted:true}):res.status(404).json({error:'Issue not found'})}const r=await pool.query('UPDATE issues SET upvotes=upvotes+1,priority=LEAST(100,priority+1),updated_at=NOW() WHERE id=$1 RETURNING *',[req.params.id]);return res.json(normalize(r.rows[0]))}const issues=await readFallback(),i=issues.find(x=>x.id===req.params.id);if(!i)return res.status(404).json({error:'Issue not found'});i.upvotes=(i.upvotes||0)+1;i.priority=Math.min(100,(i.priority||0)+1);i.updatedAt=new Date().toISOString();await writeFallback(issues);res.json(i)}catch(e){console.error(e);res.status(500).json({error:'Could not record support'})}});

app.patch('/api/issues/:id/status',async(req,res)=>{if(!authAdmin(req,res))return;const status=req.body?.status;if(!['reported','in_progress','resolved'].includes(status))return res.status(400).json({error:'Invalid status'});try{if(pool){const r=await pool.query('UPDATE issues SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[status,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Issue not found'});await pool.query('INSERT INTO issue_events(issue_id,status,note) VALUES($1,$2,$3)',[req.params.id,status,cleanText(req.body.note,500)||null]);return res.json(normalize(r.rows[0]))}const issues=await readFallback(),i=issues.find(x=>x.id===req.params.id);if(!i)return res.status(404).json({error:'Issue not found'});i.status=status;i.updatedAt=new Date().toISOString();i.events=[...(i.events||[]),{status,note:cleanText(req.body.note,500)||null,createdAt:i.updatedAt}];await writeFallback(issues);res.json(i)}catch(e){console.error(e);res.status(500).json({error:'Could not update status'})}});

app.post('/api/issues/:id/verify',async(req,res)=>{const verdict=req.body?.verdict;if(!['fixed','still_open'].includes(verdict))return res.status(400).json({error:'verdict must be fixed or still_open'});try{if(pool){const r=await pool.query('SELECT * FROM issues WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Issue not found'});if(verdict==='fixed')await pool.query("UPDATE issues SET status='resolved',updated_at=NOW() WHERE id=$1",[req.params.id]);await pool.query('INSERT INTO issue_events(issue_id,status,note) VALUES($1,$2,$3)',[req.params.id,verdict==='fixed'?'resolved':'reported',verdict==='fixed'?'Community verification: fixed':'Community verification: still open']);const u=await pool.query('SELECT * FROM issues WHERE id=$1',[req.params.id]);return res.json({...normalize(u.rows[0]),verified:verdict==='fixed'})}const issues=await readFallback(),i=issues.find(x=>x.id===req.params.id);if(!i)return res.status(404).json({error:'Issue not found'});if(verdict==='fixed')i.status='resolved';i.updatedAt=new Date().toISOString();i.events=[...(i.events||[]),{status:i.status,note:verdict==='fixed'?'Community verification: fixed':'Community verification: still open',createdAt:i.updatedAt}];await writeFallback(issues);res.json({...i,verified:verdict==='fixed'})}catch(e){console.error(e);res.status(500).json({error:'Could not record verification'})}});

app.get('/api/analytics',async(_q,res)=>{try{if(pool){const r=await pool.query(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE status='resolved') resolved,COUNT(*) FILTER(WHERE status='in_progress') in_progress,COUNT(*) FILTER(WHERE severity='high') critical,COALESCE(SUM(upvotes),0) supporters FROM issues`),x=r.rows[0],c=await pool.query('SELECT category,COUNT(*) count FROM issues GROUP BY category ORDER BY count DESC');return res.json({totalReports:Number(x.total),resolved:Number(x.resolved),inProgress:Number(x.in_progress),critical:Number(x.critical),supporters:Number(x.supporters),resolutionRate:x.total?Math.round(Number(x.resolved)/Number(x.total)*100):0,byCategory:c.rows})}const i=await readFallback(),resolved=i.filter(x=>x.status==='resolved').length;res.json({totalReports:i.length,resolved,inProgress:i.filter(x=>x.status==='in_progress').length,critical:i.filter(x=>x.severity==='high').length,supporters:i.reduce((n,x)=>n+(x.upvotes||0),0),resolutionRate:i.length?Math.round(resolved/i.length*100):0})}catch(e){console.error(e);res.status(500).json({error:'Unable to load analytics'})}});
app.get('/api/admin/issues',async(req,res)=>{if(!authAdmin(req,res))return;try{if(pool){const r=await pool.query('SELECT * FROM issues ORDER BY priority DESC,created_at DESC LIMIT 500');return res.json(r.rows.map(normalize))}res.json((await readFallback()).sort((a,b)=>(b.priority||0)-(a.priority||0)))}catch(e){console.error(e);res.status(500).json({error:'Unable to load admin issues'})}});

app.use((err,_req,res,_next)=>{console.error('KOINOS unhandled error',err);if(res.headersSent)return;res.status(err?.type==='entity.too.large'?413:500).json({error:err?.type==='entity.too.large'?'Photo/report is too large. Please use an image under 8 MB.':'Unexpected server error'})});
const initDb=async()=>{if(!pool){await ensureFallback();return}await pool.query(`CREATE TABLE IF NOT EXISTS issues(id TEXT PRIMARY KEY,title TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'other',description TEXT NOT NULL DEFAULT '',location_label TEXT,latitude DOUBLE PRECISION,longitude DOUBLE PRECISION,photo_url TEXT,anonymous BOOLEAN NOT NULL DEFAULT false,status TEXT NOT NULL DEFAULT 'reported',severity TEXT NOT NULL DEFAULT 'low',priority INTEGER NOT NULL DEFAULT 0,upvotes INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE issues ADD COLUMN IF NOT EXISTS location_label TEXT;ALTER TABLE issues ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;ALTER TABLE issues ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;ALTER TABLE issues ADD COLUMN IF NOT EXISTS photo_url TEXT;ALTER TABLE issues ADD COLUMN IF NOT EXISTS anonymous BOOLEAN DEFAULT false;ALTER TABLE issues ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'reported';ALTER TABLE issues ADD COLUMN IF NOT EXISTS severity TEXT DEFAULT 'low';ALTER TABLE issues ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;ALTER TABLE issues ADD COLUMN IF NOT EXISTS upvotes INTEGER DEFAULT 0;ALTER TABLE issues ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();ALTER TABLE issues ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();UPDATE issues SET category='other' WHERE category IS NULL;UPDATE issues SET description='' WHERE description IS NULL;UPDATE issues SET anonymous=false WHERE anonymous IS NULL;UPDATE issues SET status='reported' WHERE status IS NULL;UPDATE issues SET severity='low' WHERE severity IS NULL;UPDATE issues SET priority=0 WHERE priority IS NULL;UPDATE issues SET upvotes=0 WHERE upvotes IS NULL;UPDATE issues SET created_at=NOW() WHERE created_at IS NULL;UPDATE issues SET updated_at=NOW() WHERE updated_at IS NULL;CREATE INDEX IF NOT EXISTS issues_geo_idx ON issues(latitude,longitude);CREATE INDEX IF NOT EXISTS issues_status_idx ON issues(status);CREATE INDEX IF NOT EXISTS issues_category_idx ON issues(category);CREATE TABLE IF NOT EXISTS issue_votes(issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,device_id TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(issue_id,device_id));CREATE TABLE IF NOT EXISTS issue_events(id BIGSERIAL PRIMARY KEY,issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,status TEXT NOT NULL,note TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS issue_events_issue_idx ON issue_events(issue_id,created_at);`)};
await initDb();app.listen(PORT,()=>console.log(`KOINOS API listening on ${PORT} — ${pool?'PostgreSQL':'fallback'}`));
